# Generated by Django 5.0.7 on 2024-08-06 12:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="UserLookUp",
            fields=[
                ("id", models.IntegerField(primary_key=True, serialize=False)),
                ("log_status", models.BooleanField(default=False)),
                (
                    "designation",
                    models.CharField(
                        choices=[
                            ("FE", "Frondend Developer"),
                            ("BE", "Backend Developer"),
                            ("FD", "Fullstack Developer"),
                        ]
                    ),
                ),
                (
                    "gender",
                    models.CharField(choices=[("male", "Male"), ("female", "Female")]),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
