# Generated by Django 5.0.7 on 2024-08-06 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("admin_pannel", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userlookup",
            name="id",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
